name: Deploy personal site
on:
  #push:
  workflow_dispatch:
jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - id: vercel-environment
        name: Determine Vercel environment
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            echo "VERCEL_ENVIRONMENT=production" >> "$GITHUB_OUTPUT"
          else
            echo "VERCEL_ENVIRONMENT=preview" >> "$GITHUB_OUTPUT"
          fi
      - name: Trigger deployment workflow on mcmire/elliotwinkler.com
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPLOY_PERSONAL_SITE_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'mcmire',
              repo: 'elliotwinkler.com',
              workflow_id: 'deploy-to-vercel.yml',
              ref: 'main',
              inputs: {
                environment: process.env.VERCEL_ENVIRONMENT,
                writings_repo_ref: process.env.GITHUB_REF_NAME
              }
            })
        env:
          VERCEL_ENVIRONMENT: ${{ steps.vercel-environment.outputs.VERCEL_ENVIRONMENT }}
